### ISSUE TITLE
Doesn't Respond to messages. 

### ISSUE THREAD

**Issue by zeak6464** [tegnike/nike-ChatVRM#13]
![image](https://github.com/tegnike/nike-ChatVRM/assets/2738141/5bc8db33-835e-449b-9a5a-1645d469289c)

**Comment by tegnike** [comment]
Could you show me your setting?  
And developer console after sending message, you can open by pressing F12.

**Comment by zeak6464** [comment]
the issue is OpenAI , i treid Anthropic and it works now.

**Comment by tegnike** [comment]
Ok, good. I'll close.
