### ISSUE TITLE
add TTS local for other languages

### ISSUE THREAD

**Issue by zeak6464** [tegnike/nike-ChatVRM#15]
Wanting to use TTS local instead of using TTS cloud, would that be possible ?

**Comment by tegnike** [comment]
Now we can use VOICEVOX, but actually it's just for Japanese.  
Do you know good local TTS services of other languages??

**Comment by zeak6464** [comment]
on windows you could do this 

https://github.com/c4collins/local-tts

and use the command "main.exe --message "AI MESSAGE HERE" --voice 0 --rate 150"

**Comment by tegnike** [comment]
Thanks, I'll check it 👍

**Comment by yelban** [comment]
GPT-SoVITSもおすすめです。基本モデルは日本語、英語、そして中国語をサポートしています。
API方式での推論エンドポイントも提供しており、ストリームもサポートしています。
https://github.com/RVC-Boss/GPT-SoVITS

**Comment by tegnike** [comment]
@yelban 
ありがとうございます！
こちらのほうが最近も更新されていて良い感じですね。検討します！！

**Comment by zeak6464** [comment]
> GPT-SoVITSもおすすめです。基本モデルは日本語、英語、そして中国語をサポートしています。 API方式での推論エンドポイントも提供しており、ストリームもサポートしています。 https://github.com/RVC-Boss/GPT-SoVITS
> 
> `http://localhost:9883/tts_stream/?text=推論するためのメッセージ内容`

how do i set this up with the AI ?

**Comment by tegnike** [comment]
@zeak6464 

I added Style-Bert-VITS2 for multi-language TTS.
Please check it👍

#21
