### ISSUE TITLE
Style-Bert-VITS2で日本語をしゃべらせる時は、設定で言語を一度別の言語にする必要がある

### ISSUE THREAD

**Issue by JunzoKamahara** [tegnike/nike-ChatVRM#49]
音声エンジンにStyle-Bert-VITS2を設定して初めてnike-ChatVRMを使う時に、言語設定を何もいじっていないと、selectLanguageが"JA"になっていて、API呼び出しが失敗します。一度、言語設定を別のに変えてから日本語にすると"JP"になってうまくいくようになりました。

index.tsxの41行めでデフォルトが"JP"になっているのに、なぜ、"JA"が入っているかまでは追及できませんでした。
一度設定すればブラウザが覚えるようなので大きな問題ではありませんが、初めて使う人がハマりそうなので書かせていただきました。

**Comment by tegnike** [comment]
ご指摘ありがとうございます！確認しておきます！！

**Comment by tegnike** [comment]
確認しました！
こちらですが、最新版のmainで直ってないでしょうか？  
以前私もこちらの事象に気づいて直したはずだったと思ったので

**Comment by JunzoKamahara** [comment]
原因が分かりました。developで取ってきていましたがmainも同じかと思います。
introduction.tsxの37行目で、setSelectLanguage()するのにlanguageCodeを使っていますが、lib/i18n.jsでlng: "ja"を設定しているので、36行目でtoUpperCase()されて"JA"がセットされているようです。
単純に修正するだけなら、37行目をsetSelectLanguage(languageCode=="JA"?"JP":languageCode);でいいかと思いますが。
ただ、逆に設定変更後のリロードで34行目のi18n.languageのコンソール表示が"jp"になっているので、それが何故か分からなくなってしまいました。

**Comment by tegnike** [comment]
なるほど調査ありがとうございます。
数日前に追加した機能の影響のようですね、修正いたしますので少々お待ちください。

**Comment by tegnike** [comment]
頂いた修正方法で問題なさそうでした。また、不具合も確認できました。
私もなぜかはわからないのですが、動作には影響なさそうなので一旦マージしようと思います。
